version: '3'

services:
  app:
    network_mode: "host"
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/blog
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver "

    env_file:
      - ./.env.dev

    depends_on:
            - db

  db:
    image: postgres:12-alpine
    network_mode: "host"
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

#    volumes:
#      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    network_mode: "host"
  celery:
    network_mode: "host"
    restart: always
    build:
      context: .
    command: celery -A blog worker -l info
    volumes:
      - ./app:/blog
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
volumes:
  pgdata: