# Generated by Django 3.1.7 on 2021-03-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0003_auto_20210309_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='custuser',
            new_name='user',
        ),
    ]
